version: "3.9"
services:
  django:
    build: 
      context: ./django
      dockerfile: Dockerfile.dev
    volumes:
      - ./django/:/app
    environment:  
      - ENVIRONMENT='dev'
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
    environment:
      - WATCHPACK_POLLING=true
      - ENVIRONMENT='dev'