# Generated by Django 4.2.2 on 2023-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstSensor', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('secondSensor', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('thirdSensor', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
