FROM python:3.11.0-slim-bullseye

WORKDIR /app/

COPY ./requirements.txt .

RUN pip install -r requirements.txt
RUN apt-get -y update
RUN apt-get -y install curl 

COPY . .

CMD [ "/bin/bash","entrypoint.dev.sh" ]

